### ISSUE TITLE
Making an additional function for SCORE2-Diabetes 

### ISSUE THREAD

**Issue by JauntyJJS** [dvicencio/RiskScorescvd#5]
Hi @dvicencio,

Apologies for the late response. Had to recover from an elbow surgery to remove a cyst.
I can spend some time to create a separate (if I understand your plans correctly) function for SCORE2-Diabetes.
Will open a pull request when it is complete.
Please bear with me.

**Comment by dvicencio** [comment]
Amazing job, Jeremy, 

I have accepted the pull request. The function is now in the developing version of the package. I am planning to submit it to CRAN again eventually.

All the best,
Dan

**Comment by JauntyJJS** [comment]
Hi @dvicencio 

I understand that you have merged my implementation on the SCORE2-Diabetes.
Would you be able to update the documentation for this function ?

![image](https://github.com/dvicencio/RiskScorescvd/assets/9066508/77cd0b88-df81-4312-9c67-29bea55bd906)

I have made a mistake and thought that smoker is set to 1 if the patient has a smoking history instead of patient who are currently smoking.

Input integer 0 or 1 to indicate if the patient is a current smoker.

- 0 stands for patient is not a current smoker (past/former or non-smoker).
- 1 stands for patient is a current smoker.

**Comment by dvicencio** [comment]
Hi Jeremy,

I can do it, but I don't want to mess with your code. I think you could
easily do this and submit a pull request with the updated changes again.

Let me know if this works; otherwise I can give it a try.

I am planning to submit the new version to CRAN next week. Would it be okay
if I add you as author of the package? You have been really helpful and
made substantial contribution to the package.


King regards,
Dan

**Comment by JauntyJJS** [comment]
Hi @dvicencio,

I have added a pull request on the SCORE2-Diabetes documentation.

As for R package authorship, I am fine with that.

The details are as follows,

```
person(
  given = "Jeremy",
  family = "Selva",
  role = "aut",
  email = "jeremy1189.jjs@gmail.com",
  comment = c(ORCID = "0000-0002-4498-2662")
)
```
