### ISSUE TITLE
Error when calling calc_scores

### ISSUE THREAD

**Issue by zhaoc1** [dvicencio/RiskScorescvd#8]
Hi,

I followed the simulated data in the run examples, and run into an error when `calc_scores(data = cohort_xx` as following:

```
Error in env_get(env, name, default = missing_arg(), inherit = TRUE) : 
  promise already under evaluation: recursive default argument reference or earlier problems?
```

Any idea what's going on here? Thanks.

Chunyu

**Comment by dvicencio** [comment]
Hi Chunyu,

I will look into this and come back to you.

Dan

**Comment by dvicencio** [comment]
Hi Chunyu,

Did you try the test example?

It seems to be working for me.

Dan

**Comment by zhaoc1** [comment]
Yes, it was the test example that I couldn't run through.

**Comment by dvicencio** [comment]
Hi Chungyu,

It is working for me. It could be the package versions.

Please check that you have the required packages and the identical versions
due to dependencies and to avoid masking.

num_rows <- 100
# Create a larger dataset with 100 rowscohort_xx <- data.frame(
  typical_symptoms.num = as.numeric(sample(0:6, num_rows, replace = TRUE)),
  ecg.normal = as.numeric(sample(c(0, 1), num_rows, replace = TRUE)),
  abn.repolarisation = as.numeric(sample(c(0, 1), num_rows, replace = TRUE)),
  ecg.st.depression = as.numeric(sample(c(0, 1), num_rows, replace = TRUE)),
  Age = as.numeric(sample(30:80, num_rows, replace = TRUE)),
  diabetes = sample(c(1, 0), num_rows, replace = TRUE),
  smoker = sample(c(1, 0), num_rows, replace = TRUE),
  hypertension = sample(c(1, 0), num_rows, replace = TRUE),
  hyperlipidaemia = sample(c(1, 0), num_rows, replace = TRUE),
  family.history = sample(c(1, 0), num_rows, replace = TRUE),
  atherosclerotic.disease = sample(c(1, 0), num_rows, replace = TRUE),
  presentation_hstni = as.numeric(sample(10:100, num_rows, replace = TRUE)),
  Gender = sample(c("male", "female"), num_rows, replace = TRUE),
  sweating = as.numeric(sample(c(0, 1), num_rows, replace = TRUE)),
  pain.radiation = as.numeric(sample(c(0, 1), num_rows, replace = TRUE)),
  pleuritic = as.numeric(sample(c(0, 1), num_rows, replace = TRUE)),
  palpation = as.numeric(sample(c(0, 1), num_rows, replace = TRUE)),
  ecg.twi = as.numeric(sample(c(0, 1), num_rows, replace = TRUE)),
  second_hstni = as.numeric(sample(1:200, num_rows, replace = TRUE)),
  killip.class = as.numeric(sample(1:4, num_rows, replace = TRUE)),
  systolic.bp = as.numeric(sample(0:300, num_rows, replace = TRUE)),
  heart.rate = as.numeric(sample(0:300, num_rows, replace = TRUE)),
  creat = as.numeric(sample(0:4, num_rows, replace = TRUE)),
  cardiac.arrest = as.numeric(sample(c(0, 1), num_rows, replace = TRUE)),
  previous.pci = as.numeric(sample(c(0, 1), num_rows, replace = TRUE)),
  previous.cabg = as.numeric(sample(c(0, 1), num_rows, replace = TRUE)),
  aspirin = as.numeric(sample(c(0, 1), num_rows, replace = TRUE)),
  number.of.episodes.24h = as.numeric(sample(0:20, num_rows, replace = TRUE)),
  total.chol = as.numeric(sample(2:6, num_rows, replace = TRUE)),
  total.hdl = as.numeric(sample(2:5, num_rows, replace = TRUE)),
  Ethnicity = sample(c("white", "black", "asian", "other"), num_rows,
replace = TRUE),
  eGFR = as.numeric(sample(15:120, num_rows, replace = TRUE)),
  ACR = as.numeric(sample(5:1500, num_rows, replace = TRUE)),
  trace = sample(c("trace", "1+", "2+", "3+", "4+"), num_rows, replace = TRUE))


# Call the function with the cohort_xx
new_data_frame <- calc_scores(data = cohort_xx)

I copy pasted the above code and it worked fine.

Kind reagards,
Dan

**Comment by zhaoc1** [comment]
Thanks for looking into this. The same example code works for me now. I think it might because I installed a couple other packages including PooledCohort, which might resolve some of the library masking issues.
